import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "./footer/Footer";
import Navbar from "./navbar/Navbar";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--Poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cn(poppins.variable)}`}
        style={{ fontFamily: "var(--Poppins)" }}
      >
        <div>
          <Toaster
            position="top-center"
            containerClassName=""
            toastOptions={{
              duration: 3000,
              className: "",
              style: {
                background: "#f1f5f9",
                color: "#111827",
                fontSize: "15px",
              },
            }}
          />
          <Navbar />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
